### ISSUE TITLE
Migrate to MassTransit v6.0.2

### ISSUE THREAD

**Issue by PatriceMarin** [alexeyzimarev/MassTransit.EventStoreIntegration#5]
Hi Alexey,
Thanks for your sharing your work. 
I'm willing to use it for my projet but from what I see, this is not compatible with the last version of MassTransit.
Any chance you can take a look?

Thanks in advance.

**Comment by alexeyzimarev** [comment]
Yeah, definitely it cries for an upgrade. I will try to do it asap.

**Comment by PatriceMarin** [comment]
I've tried to migrate the solution but I'm having some issues in the tests project. I'm not able to resolve classes from the EventStore.ClientAPI.Embedded nuget package in the EventStoreFixture class. :(
(EmbeddedVNodeBuilder, VNodeState, EmbeddedEventStoreConnection) I don't know why...

**Comment by PatriceMarin** [comment]
Well, this could explain the issue: https://groups.google.com/forum/#!topic/event-store/oGldLmc5XRM

**Comment by alexeyzimarev** [comment]
Yes, the embedded server is long gone. We are usually run integrated tests against EventStore running in Docker.

**Comment by alexeyzimarev** [comment]
https://www.nuget.org/packages/MassTransit.EventStoreIntegration/6.0.2

**Comment by PatriceMarin** [comment]
Thanks a lot Alexey!
